{
 "title": "xiRAID",
 "description": "Monitoring dashboard for the Xinnor xiRAID software",
 "tags": [ "E4" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(node_os_info,cluster_name)"
    }
   },
   {
    "name": "xiraid_node",
    "label": "xiraid_node(s)",
    "query": {
     "query": "label_values(up{job=\"xiraid_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  background-color: #185265 !important;\n  color: #ffffff !important;\n  text-align: center;\n  padding: 2rem;\n  max-width: auto;\n  margin: 0 auto;\n\">\n  <h1 style=\"\n    margin: 0.2em 0;\n    text-transform: uppercase;\n    line-height: 1.2;\n    font-size: 2.5rem;\n  \">\n    ${cluster_name} Cluster\n  </h1>\n\n  <p style=\"\n    margin: 0.2em 0;\n    line-height: 1.2;\n    font-size: 1.2rem;\n    color: #ffd200;\n  \">You're watching xiRAID nodes(s):<br/>\n    ${xiraid_node}\n  </p>\n\n  <div style=\"\n    display: flex;\n    justify-content: center;\n    align-items: center;\n    gap: 1.5rem;\n    margin: 1.5rem 0;\n  \">\n    <img\n      src=\"https://www.e4company.com/wp-content/uploads/logo-e4-company-white.svg\"\n      alt=\"E4 Company\"\n      width=\"70\"\n      style=\"display: block;\"\n    >\n    <img\n      src=\"https://xinnor.io/img/logo-xinnor.svg\"\n      alt=\"Xinnor\"\n      width=\"200\"\n      style=\"display: block;\"\n    >\n  </div>\n\n  <p style=\"\n    text-align: right;\n    font-style: italic;\n    opacity: 0.8;\n    margin-top: 2rem;\n  \">\n    #whenperformancematters\n  </p>\n</div>\n"
   }
  },
  {
   "title": "xiRAID $xiraid_node License",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "xiraid_node",
   "collapsed": true,
   "panels": [
    {
     "title": "License informations",
     "type": "table",
     "description": "All the informations about the xiRAID license",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max(xiraid_license_info)         by (hwkey,license_creation,license_crypto_version,license_expiration,license_key,license_status,license_version)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(xiraid_license_disks)         by (hwkey)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(xiraid_license_disks_in_use)         by (hwkey)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(xiraid_license_levels)         by (hwkey)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "xiRAID $xiraid_node RAID(s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "xiraid_node" },
  {
   "title": "RAID(s) informations",
   "type": "table",
   "description": "All the RAID(s) informations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(xiraid_raid_info)         by (raid_name, uuid, level, sparepool_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_group_size)   by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_size_gib)     by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_strip_size)   by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_block_size)   by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_memory_usage_mb) by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_config)   by (raid_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(xiraid_raid_active)   by (raid_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAID(s) State",
   "type": "table",
   "description": "The status of all the xiRAIDs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "xiraid_raid_state\n  * on(raid_name, uuid)\n  group_left(state_detail)\n    xiraid_raid_state_detail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAID(s) Devices Status",
   "type": "table",
   "description": "Shows the informations and the status of all devices in each RAID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "xiraid_raid_device_state", "legendFormat": "__auto" }
   ]
  }
 ]
}