//*
// Messages to manage the spare pool.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: message_pool.proto

package xiraid_exporter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Add drives to the spare pool.
type PoolAdd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The name of the spare pool.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// The list of block devices to add to the spare pool.
	Drives        []string `protobuf:"bytes,2,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAdd) Reset() {
	*x = PoolAdd{}
	mi := &file_message_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAdd) ProtoMessage() {}

func (x *PoolAdd) ProtoReflect() protoreflect.Message {
	mi := &file_message_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAdd.ProtoReflect.Descriptor instead.
func (*PoolAdd) Descriptor() ([]byte, []int) {
	return file_message_pool_proto_rawDescGZIP(), []int{0}
}

func (x *PoolAdd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolAdd) GetDrives() []string {
	if x != nil {
		return x.Drives
	}
	return nil
}

// *
// Create the spare pool.
type PoolCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The name of the spare pool.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// The list of block devices to create the spare pool.
	Drives        []string `protobuf:"bytes,2,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolCreate) Reset() {
	*x = PoolCreate{}
	mi := &file_message_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolCreate) ProtoMessage() {}

func (x *PoolCreate) ProtoReflect() protoreflect.Message {
	mi := &file_message_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolCreate.ProtoReflect.Descriptor instead.
func (*PoolCreate) Descriptor() ([]byte, []int) {
	return file_message_pool_proto_rawDescGZIP(), []int{1}
}

func (x *PoolCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolCreate) GetDrives() []string {
	if x != nil {
		return x.Drives
	}
	return nil
}

// *
// Delete the spare pool.
type PoolDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The name of the spare pool.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolDelete) Reset() {
	*x = PoolDelete{}
	mi := &file_message_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolDelete) ProtoMessage() {}

func (x *PoolDelete) ProtoReflect() protoreflect.Message {
	mi := &file_message_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolDelete.ProtoReflect.Descriptor instead.
func (*PoolDelete) Descriptor() ([]byte, []int) {
	return file_message_pool_proto_rawDescGZIP(), []int{2}
}

func (x *PoolDelete) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
// Remove drives from the spare pool.
type PoolRemove struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The name of the spare pool.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// The list of block devices to remove from the spare pool.
	Drives        []string `protobuf:"bytes,2,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolRemove) Reset() {
	*x = PoolRemove{}
	mi := &file_message_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolRemove) ProtoMessage() {}

func (x *PoolRemove) ProtoReflect() protoreflect.Message {
	mi := &file_message_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolRemove.ProtoReflect.Descriptor instead.
func (*PoolRemove) Descriptor() ([]byte, []int) {
	return file_message_pool_proto_rawDescGZIP(), []int{3}
}

func (x *PoolRemove) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolRemove) GetDrives() []string {
	if x != nil {
		return x.Drives
	}
	return nil
}

// *
// Show info on the spare pool.
type PoolShow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The name of the spare pool.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// *
	// Size units.
	Units         *string `protobuf:"bytes,2,opt,name=units,proto3,oneof" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolShow) Reset() {
	*x = PoolShow{}
	mi := &file_message_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolShow) ProtoMessage() {}

func (x *PoolShow) ProtoReflect() protoreflect.Message {
	mi := &file_message_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolShow.ProtoReflect.Descriptor instead.
func (*PoolShow) Descriptor() ([]byte, []int) {
	return file_message_pool_proto_rawDescGZIP(), []int{4}
}

func (x *PoolShow) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PoolShow) GetUnits() string {
	if x != nil && x.Units != nil {
		return *x.Units
	}
	return ""
}

var File_message_pool_proto protoreflect.FileDescriptor

var file_message_pool_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x78, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x76, 0x32, 0x22, 0x35,
	0x0a, 0x07, 0x50, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0a, 0x50, 0x6f, 0x6f, 0x6c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x22,
	0x20, 0x0a, 0x0a, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x38, 0x0a, 0x0a, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x08, 0x50,
	0x6f, 0x6f, 0x6c, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x72, 0x6f,
	0x6e, 0x63, 0x75, 0x62, 0x33, 0x2f, 0x78, 0x69, 0x72, 0x61, 0x69, 0x64, 0x5f, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_message_pool_proto_rawDescOnce sync.Once
	file_message_pool_proto_rawDescData []byte
)

func file_message_pool_proto_rawDescGZIP() []byte {
	file_message_pool_proto_rawDescOnce.Do(func() {
		file_message_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_pool_proto_rawDesc), len(file_message_pool_proto_rawDesc)))
	})
	return file_message_pool_proto_rawDescData
}

var file_message_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_pool_proto_goTypes = []any{
	(*PoolAdd)(nil),    // 0: xraid.v2.PoolAdd
	(*PoolCreate)(nil), // 1: xraid.v2.PoolCreate
	(*PoolDelete)(nil), // 2: xraid.v2.PoolDelete
	(*PoolRemove)(nil), // 3: xraid.v2.PoolRemove
	(*PoolShow)(nil),   // 4: xraid.v2.PoolShow
}
var file_message_pool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_pool_proto_init() }
func file_message_pool_proto_init() {
	if File_message_pool_proto != nil {
		return
	}
	file_message_pool_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_pool_proto_rawDesc), len(file_message_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_pool_proto_goTypes,
		DependencyIndexes: file_message_pool_proto_depIdxs,
		MessageInfos:      file_message_pool_proto_msgTypes,
	}.Build()
	File_message_pool_proto = out.File
	file_message_pool_proto_goTypes = nil
	file_message_pool_proto_depIdxs = nil
}
